version: '3'
services:
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # WebSocket port (optional)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"  # HTTP API port
    environment:
      - INFLUXDB_DB=greenhouse  # Database name
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password  # Replace with a secure password
    volumes:
      - ./influxdb/data:/var/lib/influxdb

  node-red:
    image: nodered/node-red
    ports:
      - "1880:1880"  # Node-RED UI port
    depends_on:
      - mqtt-broker
      - influxdb
    volumes:
      - ./nodered/data:/data

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"  # Grafana UI port
    depends_on:
      - influxdb
    volumes:
      - ./grafana/data:/var/lib/grafana
